### ISSUE TITLE
Cannot create snapshot for list when the collection changes during the enumeration

### ISSUE THREAD

**Issue by godrose** [LogoFX/logofx-client-mvvm-model#17]

**Comment by glyad** [comment]
Question: IEnumerable don't allow changes during the enumeration as usually. Let me understand the bug.

**Comment by godrose** [comment]
@glyad Yes. Imagine concurrent access to the collection of items when the snapshot is being created but the collection has already changed.
Should provide some king of concurrency awareness here or tell the clients we can't support this scenario.

**Comment by godrose** [comment]
@glyad Forwarded the relevant e-mail
